todo/Models/ErrorViewModel.cs
namespace todo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

todo/Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using todoApp.DataAccess.Repository.IRepository;
using todoApp.Models;

namespace todo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

todo/Areas/User/Controllers/ToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using todoApp.Models;
using todoApp.DataAccess;
using todoApp.DataAccess.Repository.IRepository;

namespace todo.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ToDoListController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<ToDo> objTodoList = _unitOfWork.ToDoList.GetAll();
            return View(objTodoList);
        }
        public IActionResult Create()
        { 
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDo obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.ToDoList.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Record Saved successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //var toDoFromDb = _db.ToDo.Find(id);
            var toDoFromDbfirst = _unitOfWork.ToDoList.GetFirstOrDefault(c=>c.ToDoId == id); //Change it with mew interface after
            if(toDoFromDbfirst == null)
            {
                return NotFound();
            }
            
            return View(toDoFromDbfirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDo obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.ToDoList.Update(obj);  // to interface 
                _unitOfWork.Save();  // to interface unit of work 
                TempData["success"] = "Record Saved successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var toDoFromDbfirst = _unitOfWork.ToDoList.GetFirstOrDefault(c => c.ToDoId == id);//Change it with mew interface after
            if (toDoFromDbfirst == null)
            {
                return NotFound();
            }

            return View(toDoFromDbfirst);
        }
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var toDoFromDbfirst = _unitOfWork.ToDoList.GetFirstOrDefault(c => c.ToDoId == id);
            if (toDoFromDbfirst == null)
            {
                return NotFound();
            }
            _unitOfWork.ToDoList.Remove(toDoFromDbfirst);// to interface
            _unitOfWork.Save();
            TempData["success"] = "Record Delete successfully";
            return RedirectToAction("Index");
        }
    }
}

todo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using todo.Models;

namespace todo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

todo/Areas/User/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

todo/Areas/User/Views/ToDoList/Create.cshtml
@model ToDo
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add To Do</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" /> 
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DueDate"></label>
            <input type="date" asp-for="DueDate" asp-format="dateOnly" class="form-control" /> 
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Add</button>
        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-secondary" style="width:150px">
            back    
        </a>

    </div>

</form>

@section Scripts{
    @{
        <partial name= "_ValidationScriptsPartial" />
    }
}

todo/Areas/User/Views/ToDoList/Delete.cshtml
@model ToDo
@{
    ViewData["Title"] = "Delete";
}

<form method="post">
    <input asp-for="ToDoId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete To-Do</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" disabled class="form-control" />      
        </div>
        <div class="mb-3">
            <label asp-for="DueDate"></label>
            <input type="date" asp-for="DueDate" asp-format="dateOnly" disabled class="form-control" /> 
        </div>
        <button type="submit" class="btn btn-warning" style="width:150px">Delete</button>
        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-secondary" style="width:150px">
            back    
        </a>

    </div>

</form>

@section Scripts{
    @{
        <partial name= "_ValidationScriptsPartial" />
    }
}

todo/Areas/User/Views/ToDoList/Edit.cshtml
@model ToDo
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit To-Do</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" /> 
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DueDate"></label>
            <input type="date" asp-for="DueDate" asp-format="dateOnly" class="form-control" /> 
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-secondary" style="width:150px">
            back    
        </a>

    </div>

</form>

@section Scripts{
    @{
        <partial name= "_ValidationScriptsPartial" />
    }
}

todo/Areas/User/Views/ToDoList/Index.cshtml
@model IEnumerable<ToDo>
@{
    ViewData["Title"] = "Index";
}
<partial name="_NotificationPartial" />
<div class="container p-3">
    <div class="row pt-4"> 
        <div class ="col-6"> 
            <h2 class="text-primary">To Do List</h2>
        </div>
        <div class ="col-6 text-end">
            <a asp-controller="ToDoList" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-journal-plus"></i> &nbsp; Add
            </a>
            </div>
    </div>


    <table class = "table table-bordered table-striped" style = "width:100%">
        <thead>
            <tr>
                <th>
                    Sr No.
                </th>
                <th>
                    Title
                </th>
                <th>
                    Due Date
                </th>
                <th>

                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td withd="10%">
                        @obj.ToDoId
                    </td>
                    <td width="50%">
                        @obj.Title
                    </td>
                    <td width="10%">
                        @obj.DueDate.ToShortDateString()
                    </td>
                    <td width="15%">
                        <div class = "w-75 btn-group" role="group">
                            <a asp-controller="ToDoList" asp-action="Edit" asp-route-id="@obj.ToDoId" class="btn btn-outline-light mx-2"><Id class="bi bi-pencil-square"></Id>&nbsp; Edit</a>
                        </div>

                    </td>
                    <td width = "15%">
                        <div class = "w-75 btn-group" role="group">
                            <a asp-controller="ToDoList" asp-action="Delete" asp-route-id="@obj.ToDoId" class="btn btn-outline-warning mx-2"><i class="bi bi-trash"></i>&nbsp; Delete</a>
                        </div>

                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/todo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @*<li class="nav-item">
                  <a class="dropdown-item" asp-area="" asp-controller="ToDoList" asp-action="Index">ToDo</a>
                </li>*@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Utility</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="ToDoList" asp-action="Index">ToDo</a>
                            <a class="dropdown-item" href="#">To-Do Audit</a>
                        </div>
                    </li>
                </ul>
                @*<partial name="_LoginPartial" />*@
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - todo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

todo/Views/Shared/_NotificationPartial.cshtml
@if(TempData["success"]!= null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if(TempData["error"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}